config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "home/index"

  root "rooms#index"

  
  resources :rooms do
    resources :messages, shallow: true
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "/room/summary" => "rooms#summary"

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
    validates :name, presence: true
    has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_room, only: %i[ index new create ]
  before_action :set_message, only: %i[ show edit update destroy ]

  # GET /messages or /messages.json
  def index
    if params[:room_id]
      @room = Room.find(params[:room_id])
      @messages = @room.messages
    else
      @messages = []
    end  
  end

  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = @room.messages.build
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    @message = @room.messages.build(message_params)

    respond_to do |format|
      if @message.save
        @message.broadcast_append_to @message.room, partial: @message, 
          locals: { message: @message }, target: "message-list"
        format.html { redirect_to @message, notice: "Message was successfully created." }
        format.json { render :show, status: :created, location: @message }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to room_path(@room), notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    room = @message.room  # Get the room before destroying the message
    @message.destroy!

    respond_to do |format|
      @message.broadcast_remove_to @message.room, target: @message
      format.turbo_stream
      format.html { redirect_to room_messages_path(room), status: :see_other, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:content)
    end

    def set_room
      @room = Room.find(params[:room_id])
    end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
    @room = @rooms[0] unless @rooms.empty?
    @messages = []
    @messages = @rooms[0].messages unless @rooms.empty?
  end

  # GET /rooms/1 or /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy!

    respond_to do |format|
      format.html { redirect_to rooms_path, status: :see_other, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def summary
    @rooms = Room.all
    render action: "summary"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.expect(room: [ :name, :description ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %>
  <p>Welcome, <%= current_user.email %></p>
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
<% else %>
  <p>Please sign in to continue</p>
  <%= link_to "Sign in", new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Realtime Chat Via P Max" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: [@room, message], id: 'message-form') do |form| %>
  <% if message.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_field :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div id="<%= dom_id message %>" class="message">
  <%= message.content %>
  <%= button_to 'Delete', message, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

app/views/messages/create.turbo_stream.erb
<%= turbo_stream.append "message-list", partial: "message", object: @message %>

app/views/messages/destroy.turbo_stream.erb
<%= turbo_stream.remove @message %>

app/views/messages/edit.html.erb
<% content_for :title, "Editing message" %>

<h1>Editing message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Show this message", message_path(@message) %> |
  <%= link_to "Back to messages", room_messages_path(@message.room) %>
</div>

app/views/messages/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Messages" %>

<h1>Messages</h1>

<div id="messages">
  <%= turbo_frame_tag 'room-messages' do %>
    <div id='message-list'>
        <% @messages.each do |message| %>
          <%= render message %>
        <% end %>
    </div>
    <%= render partial: 'messages/form', locals: {message: Message.new(room: @room)} %>
    <%= turbo_stream_from @room %>
<% end %>

</div>

<%= link_to "New message", new_room_message_path(@room), data: { turbo: false } %>

app/views/messages/new.html.erb
<% content_for :title, "New message" %>

<h1>New message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Back to messages", room_messages_path(@room) %>
</div>

app/views/messages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @message %>

<div>
  <%= link_to "Edit this message", edit_message_path(@message) %> |
  <%= link_to "Back to messages", room_messages_path(@message.room) %>

  <%= button_to "Destroy this message", message_path(@message), method: :delete %>
</div>

app/views/rooms/_form.html.erb
<div id="actions">
  <%= form_with(model: room) do |form| %>
    <% if room.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>
  
        <ul>
          <% room.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div>
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/rooms/_room.html.erb
<%= link_to room_messages_path(room), 
    data: { turbo_frame: 'room-messages' } do %>
  <div class='room'>
    <%= room.name %>
  </div>
<% end %>

app/views/rooms/create.turbo_stream.erb
<%= turbo_stream.append "room-list", partial: "room", object: @room %>
<%= turbo_stream.replace "actions", partial: "form", locals: {room: Room.new(name: "Room #{Room.count + 1}")} %>

app/views/rooms/edit.html.erb
<% content_for :title, "Editing room" %>

<h1>Editing room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Show this room", @room %> |
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/index.html.erb
<div id='chatapp'>
  <div id="rooms">
    <div id='room-list'>
      <% @rooms.each do |room| %>
        <%= render "room", room: room %>
      <% end %>
    </div>
    <%= render partial: 'form', locals: {room: Room.new(name: "Room #{Room.count + 1}")} %>
  </div>

  <div id='messages'>
    <%= turbo_frame_tag 'room-messages' do %>
      <div id='message-list'>
        <% @messages.each do |message| %>
          <%= render message %>
        <% end %>
      </div>
      <%= render partial: 'messages/form', locals: {message: Message.new(room: @room)} %>
      <%= turbo_stream_from @room %>
    <% end %>
  </div>  

</div>

app/views/rooms/new.html.erb
<% content_for :title, "New room" %>

<h1>New room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @room %>

<div>
  <%= link_to "Edit this room", edit_room_path(@room) %> |
  <%= link_to "Back to rooms", rooms_path %>

  <%= button_to "Destroy this room", @room, method: :delete %>
</div>

app/views/rooms/summary.html.erb
<h1>Room Summary</h1>

<table>
  <tr>
    <th>Room</th>
    <th># Messages</th>
  </tr>
  <% @rooms.each do |room| %>
    <tr>
      <td><%= room.name %></td>
      <td>TBD</td>
    </tr>
  <% end %>
</table>